# Generated by Django 5.0.6 on 2024-06-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionariosIA', '0002_cuestiones_diciultad_cuestiones_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuestiones',
            old_name='diciultad',
            new_name='dificultad',
        ),
    ]
