# Generated by Django 5.0.6 on 2024-06-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionariosIA', '0006_remove_jugadores_id_alter_jugadores_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='cuestiones_acertadas',
            field=models.JSONField(blank=True, default='{"facil": 0, "intermedio": 0, "dificil": 0}', null=True),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='cuestiones_jugadas',
            field=models.JSONField(blank=True, default='{"facil": 0, "intermedio": 0, "dificil": 0}', null=True),
        ),
    ]
