# Generated by Django 5.0.6 on 2024-06-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionariosIA', '0007_alter_jugadores_cuestiones_acertadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='cuestiones_acertadas',
            field=models.JSONField(blank=True, default='{"Facil": 0, "Intermedio": 0, "Dificil": 0}', null=True),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='cuestiones_jugadas',
            field=models.JSONField(blank=True, default='{"Facil": 0, "Intermedio": 0, "Dificil": 0}', null=True),
        ),
    ]
