# Generated by Django 5.0.6 on 2024-06-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionariosIA', '0008_alter_jugadores_cuestiones_acertadas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicsExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
    ]
