# Generated by Django 5.0.6 on 2024-06-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_articulos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='cantidad',
            field=models.IntegerField(default=30),
        ),
    ]
