# Generated by Django 5.0.6 on 2024-06-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_articulos_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
