# Generated by Django 5.0.6 on 2024-06-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_pedidos_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='articulos',
            name='enWeb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articulos',
            name='fertilizante',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='articulos',
            name='riego',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='articulos',
            name='transplante',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
