# Generated by Django 5.0.6 on 2024-06-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0005_articulos_descripcion_articulos_enweb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='fertilizante',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_articulos'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='riego',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='transplante',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
